# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
pool:
  name: demopipeline
stages:
- stage: __default
  jobs:
  - deployment: VMDeploy
    displayName: Deploy to VM
    environment:
      name: env-demopipeline
      resourceName: dsv-linux-01
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          
