# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
pool:
  name: demopipeline
stages:
- stage: __default
  jobs:
  - deployment: VMDeploy
    displayName: Deploy to VM
    environment:
      name: env-demopipeline
      resourceName: dsv-linux-01
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'specific'
              project: '872b5e40-c4d3-4422-a791-daff8935cd8d'
              pipeline: '13'
              buildVersionToDownload: 'latest'
              downloadType: 'single'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '872b5e40-c4d3-4422-a791-daff8935cd8d'
              definition: '13'
              buildVersionToDownload: 'latest'
              targetPath: '$(Pipeline.Workspace)'
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'specific'
              project: '872b5e40-c4d3-4422-a791-daff8935cd8d'
              pipeline: '13'
              buildVersionToDownload: 'latest'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'